apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# DO NOT specify namespace here - let ArgoCD handle it
# namespace: traffic-capture-dev  # REMOVED

resources:
  - ../../base/namespace-scoped

commonLabels:
  environment: staging
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/name: traffic-capture
  app.kubernetes.io/part-of: istio-traffic-capture

patchesStrategicMerge:
  - config-patch.yaml
  - resource-patch.yaml
