# Lower resources for dev environment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passthrough-proxy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: proxy
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-collector
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: collector
        resources:
          requests:
            memory: "128Mi"
            cpu: "25m"
          limits:
            memory: "256Mi"
            cpu: "100m"