apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace-scoped deployment for dev/test environments
# VirtualService is deployed in the same namespace

resources:
  # ArgoCD hook to label namespace with istio-injection=enabled
  - namespace-job.yaml
  - traffic-collector.yaml
  - passthrough-proxy.yaml
  - proxy-configmap.yaml
  - proxy-code-configmap.yaml
  - example-app.yaml
  - test-client.yaml
  - namespace-virtualservice.yaml
  - destination-rules.yaml
  - routing-docs-configmap.yaml
  - sidecar-config.yaml

commonLabels:
  app.kubernetes.io/name: traffic-capture
  app.kubernetes.io/part-of: istio-traffic-capture
  app.kubernetes.io/managed-by: argocd