apiVersion: apps/v1
kind: Deployment
metadata:
  name: passthrough-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passthrough-proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: passthrough-proxy
        sidecar.istio.io/inject: "false"  # NO SIDECAR for proxy
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: proxy
        image: node:16-alpine
        command: ["/bin/sh", "-c", "mkdir -p /app && cp /config/server.js /app/server.js && node /app/server.js"]
        env:
        - name: SAMPLING_RATE
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: sampling_rate
        - name: COLLECTOR_URL
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: collector_url
        - name: MAX_BODY_SIZE
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: max_body_size
        - name: MASK_SENSITIVE_DATA
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: mask_sensitive_data
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: proxy
        - containerPort: 8081
          name: health
        volumeMounts:
        - name: proxy-code
          mountPath: /config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: proxy-code
        configMap:
          name: proxy-code
---
apiVersion: v1
kind: Service
metadata:
  name: passthrough-proxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: proxy
  - port: 8081
    targetPort: 8081
    name: health
  selector:
    app: passthrough-proxy
---
# ServiceAccount for enhanced security
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-sa