apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Global routing deployment for production
# VirtualService is deployed in istio-system namespace

resources:
  - traffic-collector.yaml
  - passthrough-proxy.yaml
  - proxy-configmap.yaml
  - proxy-code-configmap.yaml
  - test-client.yaml
  - destination-rules.yaml
  - routing-docs-configmap.yaml
  - global-virtualservice.yaml

commonLabels:
  app.kubernetes.io/name: traffic-capture
  app.kubernetes.io/part-of: istio-traffic-capture
  app.kubernetes.io/managed-by: argocd